# Site settings
title: Anuroop Sriram
email: anuroop.sriram@gmail.com
description: Personal webpage of Anuroop Sriram
baseurl: ""
url: ""

# Google analytics ID
google_analytics: G-H1K2L7JV60

## Contact info. (shown in footer)
# contact: >
#     <a href="mailto:anuroop.sriram@gmail.com" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Anuroop via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: publications
  - name: datasets
  # - name: code

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
